---
- name: clickhouse
  src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"

- name: vector
  src: git@github.com:t937on/vector-role.git
  scm: git
  version: "v1.1.1"

- name: lighthouse
  src: git@github.com:t937on/lighthouse-role.git
  scm: git
  version: "v1.1.1"
